#!/bin/bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'


CONFIG_FILE=~/.xdcommits/config
TARGET_DIR=~/.lolcommits
FRAMES=1
IMAGE_VIEWER=feh

XDCOMMITS_ROOT=$(dirname $(readlink -f $0))

[ -f $CONFIG_FILE ] && source $CONFIG_FILE


main() {
	if [ "$#" -lt 1 ]; then
		print_usage
		exit 1
	fi

	local command=$1
	shift

	case $command in
		help)
			print_usage
			;;
		enable|capture|disable|show)
			do_$command "$@"
			;;
		*)
			echo "Skąd znasz te prawdy? Nie z sztuki wróżenia!"
			exit 66
			;;
	esac
}

do_capture() {
	require_repo
	tmpdir=$(mktemp -d)
	trap 'rm -rf $tmpdir' EXIT
	mplayer tv:// -tv width=640:height=480:device=/dev/video0 -fps 15 -frames $FRAMES -vo jpeg:outdir=$tmpdir > /dev/null 2>&1 ||\
		{ echo "mplayer fucked up!"; exit 1; }
	images=$(find $tmpdir -name '*.jpg' | sort)
	annotate_and_save_image $images
}

annotate_and_save_image() {
	images=$*
	outdir=$(get_outdir)
	sha=$(git rev-parse --short=11 HEAD)
	alt_opts=""

	if [ "$#" -gt 1 ]; then
		filename=$outdir/${sha}.gif
		alt_opts="$alt_opts -fuzz 10% -layers Optimize"
	else
		filename=$outdir/${sha}.jpg
	fi
	commit_msg=$(git log --no-walk --format=%s)
	font=$XDCOMMITS_ROOT/Impact.ttf
	hour=$(date -d "$(git log --no-walk --format=%cD --date=iso8601)" +%H:%M)
	convert $images \
		-font $font \
		-strokewidth 2 -stroke black -fill white \
		-pointsize 48 -gravity southwest -annotate 0 "$commit_msg" \
		-pointsize 24 -gravity northeast -annotate 0 "$sha" \
		-pointsize 24 -gravity northwest -annotate 0 "$hour" \
		$alt_opts \
		$filename
}

get_outdir() {
	name=$(basename $(get_toplevel))
	outdir=$TARGET_DIR/$name
	mkdir -p $outdir
	echo $outdir
}

do_enable() {
	local git_dir
	if [ "$#" -gt 0 ]; then
		if [ "$1" = "-g" ]; then
			git_dir=/usr/share/git-core/templates
		else
			print_usage
			exit 1
		fi
	else
		require_repo
		git_dir=$(git rev-parse --git-dir)
	fi
	enable_hook $git_dir/hooks/post-commit
	exit 1
}

enable_hook() {
	local hook="$1"

	if [ ! -f "$hook" ]; then
		[ -w $(dirname $hook) ] || die "Can't write to $hook"
		echo "Writing $hook:"
		echo -e "#!/bin/sh\nxdcommits capture" | tee $hook
		chmod +x $hook
	else
		[ -w $hook ] || die "Can't write to $hook"
		grep -q -F 'xdcommits capture' $hook && die "Already enabled on $hook"
		echo "Enabling xdcommits on $hook"
		sed -i '2s/^/xdcommits capture\n/' $hook
	fi
}

do_disable() {
	die "I ain't no scipp editor! Do it yourself."
}

do_show() {
	require_repo
	sha=$(git rev-parse --short=11 HEAD)
	filename=$(get_outdir)/${sha}.*
	if [ ! -f $filename ]; then
		echo "Not captured yet!"
		exit 1
	fi
	exec $IMAGE_VIEWER $filename
}

die() {
	echo "$@"
	exit 1
}

print_usage() {
cat <<EOF
Usage: xdcommits <command> [options]

  xdcommits help        print this message
  xdcommits enable      install hook in current repository
  xdcommits enable -g   install hook in Git template (requires write access to /usr/share/git-core/templates)
  xdcommits capture     record your ugly face
  xdcommits show        display xdcommit of current commit

EOF
}

require_repo() {
	get_toplevel > /dev/null || exit 1
}

get_toplevel() {
	git rev-parse --show-toplevel
}

sanity_check() {
	local required_files="Impact.ttf"

	for file in $required_files; do
		if [ ! -f $XDCOMMITS_ROOT/$file ]; then
			echo "Missing file: $file"
			echo "Did you install xdcommits properly?"
			exit 1
		fi
	done
}

sanity_check
main "$@"
